### PR TITLE
Ch linting and formatting

### LINKED ISSUE #9: Linting and Formatting
## Description
As a developer, I want to set up ESLint for code linting and Prettier for code formatting to ensure consistent code style and maintain code quality across our project, Eddy

## Tasks 
- [x] Set up ESLint to enforce coding standards and identify potential errors 
- [x]  Configure Prettier to automatically format code according to predefined rules

## Acceptance Criteria

- ESLint is configured for code linting
- Prettier is configured for code formatting
- Prettier is configured for code formatting
- .eslintrc configuration file is created
- .prettierrc configuration file is created
- Lint and format scripts are added to package.json

## Developer Notes

- Set up ESLint to enforce coding standards and identify potential errors or code smells
- Configure Prettier to automatically format code according to predefined rules
- Customize ESLint and Prettier configurations as per project requirements
- Ensure consistency in code style across the project
- Test linting and formatting scripts to verify their effectiveness
- Document the setup process for future reference

### PR DESCRIPTION
**Pull request by EddyShimwa**
### What does this PR do?
Setting up Linting and Formating

###Description of Task to be completed?

- Set up ESLint to enforce coding standards and identify potential errors
- Configure Prettier to automatically format code according to predefined rules

#### After cloning the repo,  run the follwoing commands
- `npm install` To install dependencies
- `npm run lint` To run Es-Lint
- `npm run format` To format with Prettier

#### Any background context you want to provide?
- Linting Files are in root directory

#### What are the relevant pivotal trackers?

#9

### CODE REVIEW

**Review by wayneleon1 — COMMENTED** [review]
oky

**Review by wayneleon1 — APPROVED** [review]
Look good for me 👍

**Review by ambroisegithub — APPROVED** [review]
That's All great!!!

**Review by jkarenzi — APPROVED** [review]

**Comment by jkarenzi** [comment]
All good!

**Review by Habinezajanvier — APPROVED** [review]
LGTM

**Pull request merged**
