### PR TITLE
79 buyer should be able to checkout

### LINKED ISSUE #79: Buyer should be able to checkout
## **Description:**

As a buyer, I want to seamlessly complete the checkout process, ensuring my order is validated, inventory is updated, and my account is updated accordingly. The process should differentiate between guest users and registered buyers before proceeding to payment. Discounts and coupon codes should be applied at checkout.

### **Acceptance Criteria:**

**Checkout Request Processing:**

-  GIVEN a POST request for checkout.

### **Step 1:**

-  WHEN the requesting user/token is a buyer and the request body is validated.

### **THEN:**

-  The order should be processed.
-   Delivery and payment information should be saved to the buyer's account.
-  The inventory should be updated.
-   An order confirmation should be sent to the frontend to be displayed to the buyer.

### **Step 2:**

-  WHEN the request body fails any validation checks or the token is not of the role buyer.

### **THEN:**

-  The appropriate 4XX response message should be sent to the frontend describing the validation error.

### **Step 3:**

-  WHEN user/token is not provided.

### **THEN:**

-  Return an error message to the frontend asking the user to login to proceed with checkout.

### **Developer Notes:**

**Input Validation:**

- [ ]  All inputs should be validated for sanity.

### **Order Management:**

- [ ]  The order should be saved to the buyer's account for future use.

**User Authentication:**

- [ ]  Ensure that the user is logged in before proceeding with the checkout process.

### **Inventory Management:**

- [ ]  Update the inventory to reflect the items ordered.

### **Related Issues:**

#77 
#54 
#75 
#57

### PR DESCRIPTION
**Pull request by ambroisegithub**
### **Implement Buyer Checkout Functionality**

**Description:**

This pull request addresses the user story of enabling buyers to seamlessly complete the checkout process. It ensures that orders are validated, inventory is updated, and accounts are appropriately managed. Additionally, it distinguishes between guest users and registered buyers and applies discounts and coupon codes at checkout.

**Acceptance Criteria:**

**Checkout Request Processing:**

**Step 1:**

- WHEN a POST request for checkout is received, and the requesting user/token is a buyer and the request body is validated.
- THEN the order should be processed.
- Delivery and payment information should be saved to the buyer's account.
- The inventory should be updated.
- An order confirmation should be sent to the frontend to be displayed to the buyer.

**Step 2:**

- WHEN the request body fails any validation checks or the token is not of the role buyer.
- THEN the appropriate 4XX response message should be sent to the frontend describing the validation error.

**Step 3:**

- WHEN user/token is not provided.
- THEN return an error message to the frontend asking the user to log in to proceed with checkout.

**Developer Notes:**

**Input Validation:**

- [ ] All inputs should be validated for sanity.

**Order Management:**

- [ ] The order should be saved to the buyer's account for future use.

**User Authentication:**

- [ ] Ensure that the user is logged in before proceeding with the checkout process.

**Inventory Management:**

- [ ] Update the inventory to reflect the items ordered.

**Related Issues:**

#77
#54
#75
#57

### CODE REVIEW

**Review by niyobern — DISMISSED** [review]

**Review by Dawaic6 — APPROVED** [review]

**Review by bertrandshema — APPROVED** [review]
It is all good!

**Review by jkarenzi — APPROVED** [review]

**Comment by ambroisegithub** [comment]
Screenshot from 2024-05-21 17-09-19

**Comment by ambroisegithub** [comment]
Screenshot from 2024-05-28 13-07-51

Screenshot from 2024-05-28 13-30-27


Screenshot from 2024-05-28 13-30-46

**Comment by ambroisegithub** [comment]
Screenshot from 2024-05-28 13-30-27

**Comment by ambroisegithub** [comment]
Screenshot from 2024-05-28 13-07-51

**Comment by ambroisegithub** [comment]
Screenshot from 2024-05-28 13-30-27

**Comment by ambroisegithub** [comment]
Screenshot from 2024-05-28 13-07-51

**Comment by ambroisegithub** [comment]
Screenshot from 2024-05-21 17-09-19

**Comment by ambroisegithub** [comment]
Screenshot from 2024-05-28 13-30-46

**Review by dushimeemma — APPROVED** [review]

**Pull request merged**
