### PR TITLE
ch-database-integration-#16

### LINKED ISSUE #16: Database Integration
## Description
Here, I will set up TypeORM with PostgreSQL for our e-commerce application and define entity models to represent all the data of the application

## Tasks
- [x] Set up TypeORM for database integration
- [x] Configure TypeORM with PostgreSQL
- [x] Define the User entity models for the e-commerce

## Related Issues
#5 

## Definition of Done
- TypeORM is installed successfully
- Database is connected successfully
- Database check endpoints working

### PR DESCRIPTION
**Pull request by bertrandshema**
## What does this PR do?
set up TypeORM with PostgreSQL for our e-commerce application

## Description of Task to be completed?
- Set up TypeORM for database integration
-  Configure TypeORM with PostgreSQL
-  Define the User entity models for the e-commerce

## How should this be manually tested?
1. Start the application
2. Run a post(body: firtsName, lastName, age)  and get to this enpoints http://localhost:3000/api/v1/users

## Any background context you want to provide?
None

## What are the relevant pivotal trackers?
#16

### CODE REVIEW

**Review by wayneleon1 — COMMENTED** [review]
Everything is good but  Try to be descriptive in you PR description  , for example :
### What does this PR do ? 
Explain ..
### Description of Task completed?
Explain ..

 ### How should this be manually tested?
Explain ..

**Review by ambroisegithub — COMMENTED** [review]
Hello Bertrand, i think the user model is no longer needed because we were't starting  the operation about the users and other things I saw you reinstall existing dependencies , So you can try to use the existing ones not duplicate dependencies more.

**Review by wayneleon1 — APPROVED** [review]
Looks good for me

**Review by ambroisegithub — APPROVED** [review]
It's look good!!!

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
