### PR TITLE
Ft user should ask to chat-bot #108

### LINKED ISSUE #108: User should ask   to chat-bot any question related to  services we offer
### **1.Description**

This issue aims is to  develop a chat-bot for our e-commerce platform. Users can interact with the chat-bot to ask questions about various aspects of our business,  Including:

- **Products and Services:** Get information on what we sell (products, services, etc.)
- **Recommendations:** Receive personalized product recommendations based on their past purchases or browsing history (if available).
- **Delivery:** Learn about your delivery process, including estimated delivery times and costs.
- **Guidance:** Get assistance with navigating the platform, finding specific products, or completing orders.
- **Past Chats:** Access a history of previous conversations with the chat-bot for reference.

### **2. Acceptance Criteria**

- [ ] **Availability:** The chat-bot should be online and accessible to users 24/7.
- [ ] **User Identification:** Upon opening the chat window, the chat-bot should greet the user by name and display their registered email address (assuming users log in to our platform).
- [ ] **Chat History:** Users should be able to view a record of all past conversations with the chat-bot.
- [ ] **Public Chat:** Users can initiate public chats visible to everyone on the platform (optional, depending on your needs).
- [ ] **Real-time Response:** The chat-bot should respond to user queries immediately, providing relevant information or answers.

### **3. Developer Notes**

- **Natural Language Processing (NLP):** Utilize NLP techniques to understand the intent and context of user  queries. This allows the chat-bot to interpret the meaning behind the user's words and provide accurate responses.
- **Knowledge Base:** Develop a comprehensive knowledge base containing information about your products, services, policies, and other relevant details. The chat-bot will access this knowledge base to answer user questions.
- **Dialog Management:** Design conversation flows for the chat-bot to handle various user enquiries. This includes defining different paths based on the user's intent and providing appropriate responses at each stage.
- **Error Handling**: Implement error handling mechanisms to address situations where the chat-bot cannot understand a user's query. The bot should offer helpful suggestions or redirect users to appropriate resources.

### **4. Definition of Done**

-  A functional chat-bot is implemented on your e-commerce platform.
-  The chat-bot can answer user questions about products, services, delivery, and other relevant topics.
-  Users can access a history of past conversations with the chat-bot.
-  The chat-bot provides real-time responses to user queries.
-  The system is well documented for future maintenance and updates.

### PR DESCRIPTION
**Pull request by ambroisegithub**
### **Title: Develop Chat-Bot for E-Commerce Platform**

This pull request aims to develop a chat-bot for our e-commerce platform. Users can interact with the chat-bot to ask questions about various aspects of our business, including:

- **Products and Services:** Get information on what we sell (products, services, etc.)
- **Recommendations:** Receive personalized product recommendations based on their past purchases or browsing history (if available).
- **Delivery:** Learn about your delivery process, including estimated delivery times and costs.
- **Guidance:** Get assistance with navigating the platform, finding specific products, or completing orders.
- **Past Chats:** Access a history of previous conversations with the chat-bot for reference.

### **2. Acceptance Criteria**

- [x] **Availability:** The chat-bot should be online and accessible to users 24/7.
- [x] **User Identification:** Upon opening the chat window, the chat-bot should greet the user by name and display their registered email address (assuming users log in to our platform).
- [x] **Chat History:** Users should be able to view a record of all past conversations with the chat-bot.
- [x] **Public Chat:** Users can initiate public chats visible to everyone on the platform (optional, depending on your needs).
- [x] **Real-time Response:** The chat-bot should respond to user queries immediately, providing relevant information or answers.

### CODE REVIEW

**Review by 13XAVI — CHANGES_REQUESTED** [review]
Please Review Your Tests  and Ducumentations screenshoot

**Comment by ambroisegithub** [comment]
Screenshot from 2024-06-03 16-58-27
Screenshot from 2024-06-03 16-59-11
Screenshot from 2024-06-03 16-53-04
Screenshot from 2024-06-03 16-53-23

**Comment by ambroisegithub** [comment]
Screenshot from 2024-06-03 16-53-04

**Comment by ambroisegithub** [comment]
Screenshot from 2024-06-03 16-59-11

**Review by 13XAVI — DISMISSED** [review]

**Review by jkarenzi — APPROVED** [review]

**Review by EddyShimwa — APPROVED** [review]
Good Job!

**Review by wayneleon1 — APPROVED** [review]
Looks good

**Pull request merged**
