### PR TITLE
User is able to see recommended products

### PR DESCRIPTION
**Pull request by EddyShimwa**
#### Implemented Features:

- [x] Developed a seasonal product recommendation engine that considers occasions like summer, winter, Valentine's Day, Christmas, New Year, and other relevant events.
- [x] Integrated the seasonal recommendation engine into the application to provide buyers with tailored product suggestions based on the current season or upcoming events.

#### Definition of tasks Done:

- [x] All acceptance criteria are met, focusing on seasonal product recommendations.
- [x] Used the keywords in `tags` column
- [x] Unit tests cover the seasonal recommendation engine functionalities.
- [x] Code adheres to coding standards and best practices.
- [x] API documentation is updated to include details about seasonal product recommendation endpoints.

#### Additional Notes:

- The seasonal product recommendation system aims to enhance user engagement and satisfaction by offering relevant products based on specific occasions and seasons.
- Future enhancements may include refining the recommendation algorithm for better accuracy and exploring additional seasonal themes for product suggestions.

#### Related Issues:
#55 

### To use the Code ###
- **Clone this repository**:
  git clone https://github.com/atlp-rwanda/dynamites-ecomm-be.git
- **Endpoint**:
- `api/v1/product/recommended`

- **Run**:
`npm run dev`
- **Test-covarage**:
`npm run test:ci`

## Screenshots
sc

sc22

### CODE REVIEW

**Comment by 13XAVI** [comment]
Very nice

**Review by 13XAVI — DISMISSED** [review]
Very nice

**Review by jkarenzi — DISMISSED** [review]

**Review by wayneleon1 — DISMISSED** [review]
looks good to me

**Review by bertrandshema — APPROVED** [review]
Looks good now

**Review by ambroisegithub — APPROVED** [review]
Great Looking!!!

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
