### PR TITLE
Recover passowrd feature

### LINKED ISSUE #33: Feat: User Password Reset
### Description

As a user (vendor or buyer), I want to be able to reset my account password in case I forget it or need to change it for security reasons so that I can regain access to my account and maintain its security.

### Acceptance Criteria

- [x] Implement a password reset request API endpoint
- [x] Validate the user's email or account identifier
- [x] Generate and send a secure password reset token (e.g., via email)
- [x] Implement a password reset confirmation API endpoint
- [x] Validate the password reset token
- [x] Update the user's password with a new, securely hashed password
- [x] Implement appropriate error handling and responses
- [x] Implement input sanitization

### Related Issues

- #xx link any issues related to this

### Definition of Done

- Password reset request API endpoint is implemented and functional
- User's email or account identifier is validated
- Secure password reset tokens are generated and sent (e.g., via email)
- Password reset confirmation API endpoint is implemented and functional
- Password reset tokens are validated
- User's password is updated with a new, securely hashed password
- Appropriate error handling and responses are implemented
- Input sanitization measures are in place
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- All created endpoints are documented

### PR DESCRIPTION
**Pull request by bertrandshema**
### What does this PR do?
A user (vendor or buyer), must be able to reset the account password in case he/she forget it or need to change it for security reasons to regain access to the account and maintain its security.

### Description of Task to be completed?
- [x] Password reset request API endpoint is implemented and functional
- [x] User's email or account identifier is validated
- [x] Secure password reset tokens are generated and sent (e.g., via email)
- [x] Password reset confirmation API endpoint is implemented and functional
- [x] Password reset tokens are validated
- [x] User's password is updated with a new, securely hashed password
- [x] Appropriate error handling and responses are implemented
- [x] Input sanitization measures are in place
- [x] Unit tests are written and passing
- [x] Code adheres to coding standards and best practices
- [x] All created endpoints are documented

### How should this be manually tested?
Clone this repo git branch https://github.com/atlp-rwanda/dynamites-ecomm-be/tree/ft-recover-password
Install all dependencies npm install
Start the server npm run dev
Using postman send a PUT request containing your email in the body to generate token on  http://localhost:3000/api/v1/user/recover
Check your Email for a recover link send, copy and past the link in postman
Send a PUT request with the new password in the body

### Test Screenshot
Screenshot 2024-05-24 134605

### Swagger Documentation Screenshot
Screenshot_24-5-2024_134748_localhost

### Postman screenshots
Screenshot 2024-05-24 135035
Screenshot 2024-05-24 134924

### CODE REVIEW

**Review by jkarenzi — DISMISSED** [review]

**Review by ambroisegithub — DISMISSED** [review]
I looks good for me!!!

**Review by wayneleon1 — DISMISSED** [review]
great job

**Review by dushimeemma — CHANGES_REQUESTED** [review]
why this change?

**Comment by bertrandshema** [comment]
> why this change?



> why this change? Can you elaborate more on your question please.

**Review by wayneleon1 — APPROVED** [review]
Look good to me

**Review by dushimeemma — APPROVED** [review]
Good job 🔥

**Pull request merged**
