### PR TITLE
36 Ft admin deactivate activate 

### LINKED ISSUE #36: Feat: Account Deactivation by Platform Admin
### Description

As a platform admin, I want to be able to deactivate a user's account (vendor or buyer) for various reasons, such as policy violations, suspicious activities, or maintenance purposes. This feature will allow the admin to temporarily or permanently disable a user's access to the e-commerce platform.

### Acceptance Criteria

- [x] Implement an API endpoint for account deactivation by admin
- [x] Validate admin's authentication and authorization
- [x] Deactivate the user's account by updating the database
- [x] Revoke any active sessions or access tokens for the deactivated account
- [x] Implement appropriate error handling and responses
- [x] Implement input sanitization

### Developer Notes

- Define the API endpoint and request/response payloads for account deactivation
- Implement authentication and authorization checks for admin access
- Update the user account status in the database to indicate deactivation
- Revoke any active sessions or access tokens associated with the deactivated account
- Handle edge cases, such as failed deactivation or unauthorized access
- Write unit tests to cover different scenarios and edge cases
- Write clear API documentation for the resulting endpoint

### Related Issues

- #xx related issue title

### Definition of Done

- Account deactivation API endpoint is implemented and functional
- Admin authentication and authorization are validated
- User accounts are deactivated by updating the database
- Active sessions or access tokens for deactivated accounts are revoked
- Appropriate error handling and responses are implemented
- Input sanitization measures are in place
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation for the resulting endpoint is completed

### PR DESCRIPTION
**Pull request by ambroisegithub**
**What does this PR do?**

This pull request introduces the ability for platform administrators to deactivate user accounts (both vendors and buyers) on the e-commerce platform. This feature enables admins to temporarily or permanently disable a user's access due to policy violations, suspicious activities, or maintenance purposes.

**Description of Task to be completed:**

**The tasks included in this pull request are as follows:****

- [x] Implement an API endpoint for account deactivation by the admin.
- [x] Validate admin's authentication and authorization.
- [x] Deactivate the user's account by updating the database.
- [x] Revoke any active sessions or access tokens for the deactivated account.
- [x] Implement appropriate error handling and responses.
- [x] Implement input sanitization.

**Developer Notes:**

Here are some additional notes for developers working on this feature:

- Define the API endpoint and request/response payloads for account deactivation.
- Implement authentication and authorization checks for admin access.
- Update the user account status in the database to indicate deactivation.
- Revoke any active sessions or access tokens associated with the deactivated account.
- Handle edge cases, such as failed deactivation or unauthorized access.
- Write unit tests to cover different scenarios and edge cases.
- Write clear API documentation for the resulting endpoint.

**Related Issues:**

#46 

**Definition of Done:**

To consider this task complete, the following criteria must be met:

-  Account deactivation API endpoint is implemented and functional.
- Admin authentication and authorization are validated.
- User accounts are deactivated by updating the database.
- Active sessions or access tokens for deactivated accounts are revoked.
- Appropriate error handling and responses are implemented.
- Input sanitization measures are in place.
- Unit tests are written and passing.
- Code adheres to coding standards and best practices.
- API documentation for the resulting endpoint is completed.

### CODE REVIEW

**Comment by ambroisegithub** [comment]
Screenshot from 2024-05-17 17-48-32

**Comment by ambroisegithub** [comment]
Screenshot from 2024-05-19 18-08-11

**Review by wayneleon1 — DISMISSED** [review]
Looks Good to me!

**Review by jkarenzi — APPROVED** [review]

**Review by jkarenzi — DISMISSED** [review]

**Review by bertrandshema — DISMISSED** [review]
It is all good for mreging.

**Review by wayneleon1 — DISMISSED** [review]
good job

**Review by bertrandshema — APPROVED** [review]
It is good now.

**Review by wayneleon1 — APPROVED** [review]

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
