### PR TITLE
Subscribe

### PR DESCRIPTION
**Pull request by 13XAVI**
### Task Completed

- Implement subscribe Endpoint for use to Keep In touch
- Implement appropriate error handling and responses
- Write appropriate unit tests
- Write appropriate documentation for the resulting endpoint
#125

### CODE REVIEW

**Review by ambroisegithub — DISMISSED** [review]
It looks good for merge!!!

**Review by EddyShimwa — DISMISSED** [review]
Good Job!

**Review by niyobern — DISMISSED** [review]

**Review by jkarenzi — DISMISSED** [review]

**Review by niyobern — DISMISSED** [review]

**Review by wayneleon1 — DISMISSED** [review]

**Review by wayneleon1 — APPROVED** [review]
well done

**Review by EddyShimwa — APPROVED** [review]
👍

**Review by Dawaic6 — APPROVED** [review]

**Review by dushimeemma — APPROVED** [review]

**Pull request merged**
